### ISSUE TITLE
MMock over network causes flaky test runs

### ISSUE THREAD

**Issue by HeatherBoard** [JumboInteractiveLimited/Gandalf#25]
This may take a few attempts to reproduce. If you run gandalf against mmock a number of times  you will get the error:
```
Export save failed due to error: PUT to MMock failed with status code 404
```

I also got this error: 
```
Export save failed due to error: POST to MMock failed with status code 409
```

**Comment by Nekroze** [comment]
might need to improve https://github.com/JumboInteractiveLimited/Gandalf/commit/c9615360efa24468cc29402631ca837e9a35d0fc#diff-04df6d028be2fa32375cf371701394efR77 to better handle this eventuality that causes slightly flaky tests.
