### ISSUE TITLE
unable to resolve library dependency 

### ISSUE THREAD

**Issue by lucky541** [JumboInteractiveLimited/Gandalf#37]
please check : https://stackoverflow.com/questions/61673893/unable-to-setup-gandalf-go#
i am trying to setup sample testcase but getting error `package github.com/jmartin82/mmock/definition: cannot find package "github.com/jmartin82/mmock/definition" in any of: $GOROOT and $GOPATH`

**Comment by Nekroze** [comment]
Hi @lucky541

Gandalf's `go.mod` file currently states it supports mmock v2.5.0 which [does have the missing subpackage](https://github.com/jmartin82/mmock/tree/v2.5.0) however I can see that the latest versions of mmock do not so this must have changed in a more recent version.

For an immediate fix you should be able to run `git checkout v2.5.0` in the mmock repository you have in your GOPATH or if you are using go modules then `go module download` should get the correct version for you where something like `go get` may have grabbed the latest versions and caused this issue.

Also please note that Gandalf still uses custom `go test` flags which got deprecated in a newer version of go (1.13 iirc) and as such must be used with a slightly older verison of go (I can confirm it works with 1.12) until they are replaced sadly, however the recommended way to run Gandalf is within a docker container where this is much easier to deal with.
